name: Deploy to Dokku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to Dokku using Dokku Action
        uses: dokku/dokku-action@master
        with:
          git_remote_url: ssh://dokku@${{secrets.VPS_IP}}/kelodi-backend
          branch: master
          ssh_private_key: ${{secrets.VPS_SSH_PRIVATE_KEY}}
