name: Deploy to Dokku

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Dokku Environment Variables
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_IP }}
          username: dokku
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            dokku config:set kelodi-backend KELODI_DB_DSN="${{ secrets.KELODI_DB_DSN }}" && \
            dokku config:set kelodi-backend SMTP_USER="${{ secrets.SMTP_USER }}" && \
            dokku config:set kelodi-backend SMTP_PASSWORD="${{ secrets.SMTP_PASSWORD }}" && \
            dokku config:set kelodi-backend SMTP_SENDER="${{ secrets.SMTP_SENDER }}" && \
            dokku config:set kelodi-backend SMTP_HOST="${{ secrets.SMTP_HOST }}"

      - name: Deploy to Dokku using Dokku Action
        uses: dokku/dokku-action@master
        with:
          git_remote_url: ssh://dokku@${{ secrets.VPS_IP }}/kelodi-backend
          branch: master
          ssh_private_key: ${{secrets.VPS_SSH_PRIVATE_KEY}}
